[package]
name = 'token_transfer_extended'
version = '1.0.0'
upgrade_policy = 'immutable'

[dependencies.AptosToken]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token'

[addresses]
token_exdened = "0xdd379161eb6be1d665219b9afb9f4f7694b27f0d42ea1353f3a8b1a2260e7ce9"
